# Generated by Django 5.2.7 on 2025-10-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sweet_type', models.CharField(choices=[('weight', 'By Weight'), ('count', 'By Count')], max_length=10)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tray_weight_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('sweet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.sweet')),
            ],
        ),
    ]
