# Generated by Django 5.2.7 on 2025-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
