# Generated by Django 5.2.7 on 2025-10-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoiceitem_unit_price_override'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='gross_weight_g',
            new_name='gross_weight_kg',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='tray_weight_g',
            new_name='tray_weight_kg',
        ),
    ]
