# Generated by Django 5.2.7 on 2025-10-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_gross_weight_g_invoiceitem_gross_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_type',
            field=models.CharField(choices=[('GST', 'GST'), ('Non-GST', 'Non-GST')], default='GST', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=10),
        ),
    ]
