# Generated by Django 5.2.7 on 2025-10-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_bill_type_invoice_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('GST', 'GST'), ('Non-GST', 'Non-GST')], default='GST', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=10, null=True),
        ),
    ]
