# Generated by Django 5.2.7 on 2025-10-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_invoice_bill_type_alter_invoice_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dm_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
